//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  siteContent: SiteContent;
  siteContentConnection: SiteContentConnection;
  devNotes: DevNotes;
  devNotesConnection: DevNotesConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteContentArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteContentConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteContentFilter>;
};


export type QueryDevNotesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDevNotesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DevNotesFilter>;
};

export type DocumentFilter = {
  siteContent?: InputMaybe<SiteContentFilter>;
  devNotes?: InputMaybe<DevNotesFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = SiteContent | DevNotes | Folder;

export type SiteContent = Node & Document & {
  __typename?: 'SiteContent';
  title: Scalars['String']['output'];
  eyebrow?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  ctaLabel?: Maybe<Scalars['String']['output']>;
  ctaHref?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type SiteContentFilter = {
  title?: InputMaybe<StringFilter>;
  eyebrow?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
  ctaLabel?: InputMaybe<StringFilter>;
  ctaHref?: InputMaybe<StringFilter>;
};

export type SiteContentConnectionEdges = {
  __typename?: 'SiteContentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<SiteContent>;
};

export type SiteContentConnection = Connection & {
  __typename?: 'SiteContentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteContentConnectionEdges>>>;
};

export type DevNotes = Node & Document & {
  __typename?: 'DevNotes';
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DevNotesFilter = {
  body?: InputMaybe<RichTextFilter>;
};

export type DevNotesConnectionEdges = {
  __typename?: 'DevNotesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DevNotes>;
};

export type DevNotesConnection = Connection & {
  __typename?: 'DevNotesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DevNotesConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateSiteContent: SiteContent;
  createSiteContent: SiteContent;
  updateDevNotes: DevNotes;
  createDevNotes: DevNotes;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateSiteContentArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteContentMutation;
};


export type MutationCreateSiteContentArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteContentMutation;
};


export type MutationUpdateDevNotesArgs = {
  relativePath: Scalars['String']['input'];
  params: DevNotesMutation;
};


export type MutationCreateDevNotesArgs = {
  relativePath: Scalars['String']['input'];
  params: DevNotesMutation;
};

export type DocumentUpdateMutation = {
  siteContent?: InputMaybe<SiteContentMutation>;
  devNotes?: InputMaybe<DevNotesMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  siteContent?: InputMaybe<SiteContentMutation>;
  devNotes?: InputMaybe<DevNotesMutation>;
};

export type SiteContentMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  ctaLabel?: InputMaybe<Scalars['String']['input']>;
  ctaHref?: InputMaybe<Scalars['String']['input']>;
};

export type DevNotesMutation = {
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type SiteContentPartsFragment = { __typename: 'SiteContent', title: string, eyebrow?: string | null, body?: any | null, ctaLabel?: string | null, ctaHref?: string | null };

export type DevNotesPartsFragment = { __typename: 'DevNotes', body?: any | null };

export type SiteContentQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SiteContentQuery = { __typename?: 'Query', siteContent: { __typename: 'SiteContent', id: string, title: string, eyebrow?: string | null, body?: any | null, ctaLabel?: string | null, ctaHref?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SiteContentConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteContentFilter>;
}>;


export type SiteContentConnectionQuery = { __typename?: 'Query', siteContentConnection: { __typename?: 'SiteContentConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SiteContentConnectionEdges', cursor: string, node?: { __typename: 'SiteContent', id: string, title: string, eyebrow?: string | null, body?: any | null, ctaLabel?: string | null, ctaHref?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type DevNotesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type DevNotesQuery = { __typename?: 'Query', devNotes: { __typename: 'DevNotes', id: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type DevNotesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DevNotesFilter>;
}>;


export type DevNotesConnectionQuery = { __typename?: 'Query', devNotesConnection: { __typename?: 'DevNotesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'DevNotesConnectionEdges', cursor: string, node?: { __typename: 'DevNotes', id: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const SiteContentPartsFragmentDoc = gql`
    fragment SiteContentParts on SiteContent {
  __typename
  title
  eyebrow
  body
  ctaLabel
  ctaHref
}
    `;
export const DevNotesPartsFragmentDoc = gql`
    fragment DevNotesParts on DevNotes {
  __typename
  body
}
    `;
export const SiteContentDocument = gql`
    query siteContent($relativePath: String!) {
  siteContent(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteContentParts
  }
}
    ${SiteContentPartsFragmentDoc}`;
export const SiteContentConnectionDocument = gql`
    query siteContentConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteContentFilter) {
  siteContentConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteContentParts
      }
    }
  }
}
    ${SiteContentPartsFragmentDoc}`;
export const DevNotesDocument = gql`
    query devNotes($relativePath: String!) {
  devNotes(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...DevNotesParts
  }
}
    ${DevNotesPartsFragmentDoc}`;
export const DevNotesConnectionDocument = gql`
    query devNotesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: DevNotesFilter) {
  devNotesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...DevNotesParts
      }
    }
  }
}
    ${DevNotesPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      siteContent(variables: SiteContentQueryVariables, options?: C): Promise<{data: SiteContentQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteContentQueryVariables, query: string}> {
        return requester<{data: SiteContentQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteContentQueryVariables, query: string}, SiteContentQueryVariables>(SiteContentDocument, variables, options);
      },
    siteContentConnection(variables?: SiteContentConnectionQueryVariables, options?: C): Promise<{data: SiteContentConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteContentConnectionQueryVariables, query: string}> {
        return requester<{data: SiteContentConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteContentConnectionQueryVariables, query: string}, SiteContentConnectionQueryVariables>(SiteContentConnectionDocument, variables, options);
      },
    devNotes(variables: DevNotesQueryVariables, options?: C): Promise<{data: DevNotesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DevNotesQueryVariables, query: string}> {
        return requester<{data: DevNotesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DevNotesQueryVariables, query: string}, DevNotesQueryVariables>(DevNotesDocument, variables, options);
      },
    devNotesConnection(variables?: DevNotesConnectionQueryVariables, options?: C): Promise<{data: DevNotesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DevNotesConnectionQueryVariables, query: string}> {
        return requester<{data: DevNotesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DevNotesConnectionQueryVariables, query: string}, DevNotesConnectionQueryVariables>(DevNotesConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "/api/tina/gql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  